services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_password
      - POSTGRES_DB=mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    container_name: mlflow-server
    restart: always
    ports:
      - "5000:5000"
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000
      --backend-store-uri postgresql://mlflow_user:mlflow_password@postgres:5432/mlflow_db
      --default-artifact-root ./mlruns
    depends_on:
      - postgres

  dispatch-monitor:
    build: .
    container_name: dispatch-monitor
    volumes:
      - ./datasets:/app/datasets
      - ./models:/app/models
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    shm_size: '8g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  train:
    build: .
    container_name: dispatch-monitor-training
    command: >
      python src/train.py 
      --data dispatch_data.yaml 
      --epochs 50 
      --batch-size 8 
      --weights yolov8n.pt
    volumes:
      - ./datasets:/app/datasets
      - ./models:/app/models
      - ./src:/app/src
      - ./dispatch_data.yaml:/app/dispatch_data.yaml
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  postgres_data: